use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::{Modify, OpenApi};

/// The OpenAPI document is generated from the same `#[utoipa::path]` attributes
/// that sit on the handlers, so the spec cannot drift from the implementation
/// the way a hand-maintained YAML file does.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "nom-inal API",
        version = "0.3.0",
        description = "Weight, macro, calorie, recipe and food-database tracking."
    ),
    servers((url = "/api/v1", description = "Versioned API root")),
    paths(
        crate::routes::health,
        crate::routes::auth::register,
        crate::routes::auth::registration,
        crate::routes::auth::login,
        crate::routes::auth::me,
        crate::routes::profile::get_profile,
        crate::routes::profile::update_profile,
        crate::routes::profile::focus_options,
        crate::routes::profile::focus_preview,
        crate::routes::profile::set_focus,
        crate::routes::weights::list,
        crate::routes::weights::upsert,
        crate::routes::weights::get_one,
        crate::routes::weights::patch,
        crate::routes::weights::delete,
        crate::routes::weights::stats,
        crate::routes::foods::list,
        crate::routes::foods::get_one,
        crate::routes::foods::create,
        crate::routes::foods::update,
        crate::routes::foods::delete,
        crate::routes::foods::search_external,
        crate::routes::foods::barcode,
        crate::routes::foods::external_detail,
        crate::routes::foods::import,
        crate::routes::foods::export,
        crate::routes::foods::revisions,
        crate::routes::foods::revert,
        crate::routes::foods::verifications,
        crate::routes::foods::verify,
        crate::routes::foods::unverify,
        crate::routes::foods::recent,
        crate::routes::foods::add_portion,
        crate::routes::foods::remove_portion,
        crate::routes::keys::list,
        crate::routes::keys::create,
        crate::routes::keys::revoke,
        crate::routes::admin::users,
        crate::routes::admin::patch_user,
        crate::routes::admin::stats,
        crate::routes::admin::settings,
        crate::routes::admin::update_settings,
        crate::routes::recipes::list,
        crate::routes::recipes::get_one,
        crate::routes::recipes::create,
        crate::routes::recipes::update,
        crate::routes::recipes::delete,
        crate::routes::recipes::export,
        crate::routes::recipes::import_from_url,
        crate::routes::public::recipe,
        crate::routes::public::photo,
        crate::routes::account::export,
        crate::routes::account::import,
        crate::routes::recipes::from_meal,
        crate::routes::search::stream_foods,
        crate::routes::photos::list_for_weight,
        crate::routes::photos::upload_for_weight,
        crate::routes::photos::list_for_recipe,
        crate::routes::photos::upload_for_recipe,
        crate::routes::photos::serve,
        crate::routes::photos::set_caption,
        crate::routes::photos::delete,
        crate::routes::reminders::list,
        crate::routes::reminders::replace,
        crate::routes::reminders::status,
        crate::routes::targets::list,
        crate::routes::targets::get_one,
        crate::routes::targets::replace,
        crate::routes::targets::delete,
        crate::routes::targets::suggestion,
        crate::routes::diary::list,
        crate::routes::diary::day,
        crate::routes::diary::summary,
        crate::routes::diary::get_one,
        crate::routes::diary::create,
        crate::routes::diary::patch,
        crate::routes::diary::delete,
        crate::routes::diary::set_complete,
        crate::routes::estimates::tdee,
        crate::routes::estimates::projection,
        crate::routes::diary::copy,
    ),
    components(schemas(
        crate::routes::Health,
        crate::error::ErrorBody,
        crate::domain::nutrients::Nutrients,
        crate::domain::nutrients::EnergyShare,
        crate::domain::user::Profile,
        crate::domain::user::ChartMode,
        crate::domain::user::TrackingFocus,
        crate::domain::user::Units,
        crate::domain::energy::EnergyEstimate,
        crate::domain::focus::FocusPreview,
        crate::domain::focus::PreviewTarget,
        crate::routes::profile::FocusOption,
        crate::routes::profile::SetFocusRequest,
        crate::routes::profile::SetFocusResponse,
        crate::routes::targets::TargetSuggestion,
        crate::domain::user::RegisterRequest,
        crate::routes::auth::RegistrationStatus,
        crate::domain::user::LoginRequest,
        crate::domain::user::AuthResponse,
        crate::domain::user::UpdateProfileRequest,
        crate::domain::weight::WeightEntry,
        crate::domain::weight::UpsertWeightRequest,
        crate::domain::weight::PatchWeightRequest,
        crate::domain::weight::WeightStats,
        crate::domain::food::Food,
        crate::domain::food::FoodDetail,
        crate::domain::food::UpsertFoodRequest,
        crate::domain::food::ExternalFood,
        crate::domain::food::ExternalSearchResponse,
        crate::domain::food::BarcodeLookup,
        crate::domain::food::NutrientBasis,
        crate::domain::food::FoodProvenance,
        crate::domain::food::FoodRevision,
        crate::domain::food::FoodVerification,
        crate::domain::food::VerificationStatus,
        crate::domain::food::Verdict,
        crate::domain::food::VerifyRequest,
        crate::domain::food::RevertRequest,
        crate::domain::food::FoodExport,
        crate::domain::food::FoodExportBundle,
        crate::domain::food::FoodPortion,
        crate::domain::food::ExternalPortion,
        crate::domain::food::AddPortionRequest,
        crate::domain::food::RecentItem,
        crate::domain::food::RecentRecipe,
        crate::domain::api_key::ApiKey,
        crate::domain::api_key::ApiKeyScope,
        crate::domain::api_key::CreateApiKeyRequest,
        crate::domain::api_key::CreatedApiKey,
        crate::routes::admin::AdminUserRow,
        crate::routes::admin::AdminStats,
        crate::routes::admin::PatchUserRequest,
        crate::routes::admin::InstanceSettings,
        crate::routes::admin::UpdateSettingsRequest,
        crate::domain::recipe::Recipe,
        crate::domain::recipe::RecipeSummary,
        crate::domain::recipe::RecipeItem,
        crate::domain::recipe::RecipeItemInput,
        crate::domain::recipe::UpsertRecipeRequest,
        crate::domain::recipe::PublicRecipe,
        crate::domain::recipe::FoodRef,
        crate::domain::recipe::RecipeExportItem,
        crate::domain::recipe::RecipeExport,
        crate::domain::recipe::RecipeExportBundle,
        crate::domain::recipe::ImportRecipeRequest,
        crate::domain::recipe::DraftCandidate,
        crate::domain::recipe::DraftLine,
        crate::domain::recipe::RecipeDraft,
        crate::routes::account::ExportedProfile,
        crate::routes::account::ExportedTarget,
        crate::routes::account::ExportedReminder,
        crate::routes::account::ExportedDiaryEntry,
        crate::routes::account::ExportedWeight,
        crate::routes::account::ExportedPhoto,
        crate::routes::account::AccountExport,
        crate::routes::account::MergeCount,
        crate::routes::account::ImportReport,
        crate::domain::recipe::FromMealRequest,
        crate::domain::diary::DiaryEntry,
        crate::domain::diary::DiaryDay,
        crate::domain::target::Nutrient,
        crate::domain::target::TargetKind,
        crate::domain::target::NutritionTarget,
        crate::domain::target::TargetInput,
        crate::domain::target::ReplaceTargetsRequest,
        crate::domain::target::TargetProgress,
        crate::domain::photo::Photo,
        crate::routes::photos::CaptionRequest,
        crate::domain::reminder::Reminder,
        crate::domain::reminder::ReminderKind,
        crate::domain::reminder::ReminderInput,
        crate::domain::reminder::ReminderStatus,
        crate::domain::reminder::ReplaceRemindersRequest,
        crate::domain::diary::MealGroup,
        crate::domain::diary::DailyTotal,
        crate::domain::diary::DiarySummary,
        crate::domain::diary::CreateDiaryEntryRequest,
        crate::domain::diary::PatchDiaryEntryRequest,
        crate::domain::diary::SetDayCompleteRequest,
        crate::domain::diary::DayCompletion,
        crate::domain::estimate::TdeeEstimate,
        crate::domain::estimate::AdaptiveEstimate,
        crate::domain::estimate::Evidence,
        crate::domain::estimate::Confidence,
        crate::domain::estimate::Projection,
        crate::domain::estimate::TrendEvidence,
        crate::domain::estimate::TrendSummary,
        crate::domain::estimate::ByDatePlan,
        crate::domain::diary::CopyDiaryRequest,
        crate::domain::diary::CopyDiaryResult,
    )),
    modifiers(&BearerAuth),
    tags(
        (name = "meta", description = "Service health and spec"),
        (name = "auth", description = "Registration and sign-in"),
        (name = "profile", description = "Profile and daily targets"),
        (name = "weights", description = "Weight and body-fat tracking"),
        (name = "foods", description = "Food database, USDA/Open Food Facts lookup, barcodes"),
        (name = "recipes", description = "Recipes and computed macros"),
        (name = "targets", description = "Daily goals (floors) and budgets (ceilings)"),
        (name = "search", description = "Streaming, fuzzy food search"),
        (name = "photos", description = "Photos attached to weigh-ins (private) and recipes (visible to whoever can see the recipe)"),
        (name = "reminders", description = "Cadence nudges derived from your own data"),
        (name = "diary", description = "Calorie and macro logging"),
        (name = "estimates", description = "Expenditure and goal projection from your own complete days and weigh-ins"),
        (name = "keys", description = "Personal API keys for scripts and dashboards"),
        (name = "public", description = "Shared recipes and their photos, readable without signing in"),
        (name = "account", description = "Everything an account owns, exported as one document and merged back in"),
        (name = "admin", description = "Instance administration"),
    )
)]
pub struct ApiDoc;

struct BearerAuth;

impl Modify for BearerAuth {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer",
                SecurityScheme::Http(
                    HttpBuilder::new()
                        .scheme(HttpAuthScheme::Bearer)
                        .bearer_format("JWT")
                        .build(),
                ),
            );
        }
    }
}
